version: '3'
services:
  postgres:
    image: 'postgres:${POSTGRES_VERSION:-14}'
    container_name: 'postgres'
    restart: always
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_MULTIPLE_DATABASES: '${DATABASE_CREATE:-dbtest}'
      POSTGRES_USER: '${POSTGRES_USER:-postgres}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-root}'
      POSTGRES_INITDB: |
        sed -i -e 's/max_connections.*/max_connections = 5000/' /var/lib/postgresql/data/postgresql.conf
        sed -i -e 's/#log_min_duration_statement = .*/log_min_duration_statement = 0/' /var/lib/postgresql/data/postgresql.conf
    volumes:
      - lampp-postgres:/var/lib/postgresql/data/
      - './docker/create_databases_postgres.sh:/docker-entrypoint-initdb.d/create_databases_postgres.sh'
    stdin_open: true
    networks:
      - network

  mariadb:
    image: 'mariadb:${MARIADB_VERSION:-10}'
    container_name: 'mariadb'
    restart: always
    environment:
      MARIADB_MULTIPLE_DATABASES: '${DATABASE_CREATE:-dbtest}'
      MARIADB_USER: '${DATABASE_USER:-mariadb}'
      MARIADB_PASSWORD: '${MARIADB_PASSWORD:-root}'
      MARIADB_ROOT_PASSWORD: '${MARIADB_PASSWORD:-root}'
    volumes:
      - lampp-mysql:/var/lib/mysql
      - './docker/create_databases_mariadb.sh:/docker-entrypoint-initdb.d/create_databases_mariadb.sh'
    ports:
      - '${MARIADB_PORT:-3306}:3306'
    stdin_open: true
    networks:
      - network
      
  redis:
    image: 'redis:${REDIS_VERSION:-alpine}'
    container_name: 'redis'
    restart: always
    ports:
        - '${REDIS_PORT:-6379}:6379'
    volumes:
        - 'lampp-redis:/data'
    networks:
        - network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s  

  mailpit:
    image: 'axllent/mailpit:${MAILPIT_VERSION:-latest}'
    container_name: 'mailpit'
    restart: always
    ports:
      - '${MAILPIT_WEB_PORT:-8026}:8025' # port web
    networks:
        - network

  vscode:
    image: 'linuxserver/code-server'
    container_name: 'vscode'
    restart: always
    ports:
      - '${VSCODE_WEB_PORT:-8443}:8443' # port web
    environment:
      PASSWORD: '${VSCODE_PASSWORD:-123456}'
      SUDO_PASSWORD: '${VSCODE_SUDO_PASSWORD:-123456}'
    volumes:
      - lampp-vscode:/config/workspace
      - './:/workspace'
    depends_on:
      - postgres
      - mariadb
      - projects
    links:
      - postgres
      - mariadb
      - projects
    networks:
        - network

  projects:
    image: 'php:${PHP_VERSION:-8.1}-apache'
    # image: php:8.1-apache
    container_name: 'projects'
    restart: always
    tty: true
    build:
      context: ./docker
      dockerfile: Dockerfile
      # dockerfile: Dockerfile-Apache
      args:
        uid: '${USER_UID:-1000}'
        NODE_VERSION: '${NODE_VERSION:-14.21.3}'
        PHP_VERSION: '${PHP_VERSION:-8.1}'
        XDEBUG_VERSION: '${PHP_XDEBUG_VERSION:-3.1.5}'
        XDEBUG_CLIENT_PORT: '${PHP_XDEBUG_CLIENT_PORT:-9003}'
    environment:
      PHP_VERSION: '${PHP_VERSION:-8.1}'
      XDEBUG_MODE: '${PHP_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${PHP_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      APACHE_RUN_USER: '${APACHE_USER:-www-data}'
      APACHE_RUN_GROUP: '${APACHE_GROUP:-www-data}'
    ports:
      - '80:80'
    volumes:
      - './projects:/var/www'
      - './docker/.bashrc:/root/.bashrc'
      - './docker/hosts:/etc/hosts'
      - './docker/lamp:/usr/local/bin/lamp'
      - './docker/apache/conf/dir.conf:/etc/apache2/mods-enabled/dir.conf'
      - './docker/apache/sites:/etc/apache2/sites-available'
      - './docker/apache/sites:/etc/apache2/sites-enabled'
    depends_on:
      - postgres
      - mariadb
      - redis
      - mailpit
    links:
      - postgres
      - mariadb
      - redis
      - mailpit
    networks:
      - network
    
networks:
  network:
    driver: bridge

volumes:
  lampp-postgres:
        driver: local
  lampp-mysql:  
        driver: local
  lampp-redis:
      driver: local
  lampp-minio:
      driver: local
  lampp-vscode:
      driver: local
